FROM openjdk:19-buster

# Diretório dos plugins
ENV MB_PLUGINS_DIR=/home/plugins/

# Baixa o Metabase e o driver DuckDB
ADD https://downloads.metabase.com/v0.52.4/metabase.jar /home
ADD https://github.com/MotherDuck-Open-Source/metabase_duckdb_driver/releases/download/0.2.12/duckdb.metabase-driver.jar /home/plugins/

# Copia o banco DuckDB já criado localmente (opcional)
COPY ./database/dw.duckdb /data/database/dw.duckdb

# Permissão no plugin
RUN chmod 744 /home/plugins/duckdb.metabase-driver.jar

# Configurações de memória da JVM
ENV JAVA_OPTS="-Xmx1024m -Xms512m"

# Comando de inicialização
CMD ["sh", "-c", "java $JAVA_OPTS -jar /home/metabase.jar"]

#docker run --name metaduck_cloud -d -p 80:3000 -m 2GB -e MB_PLUGINS_DIR=/home/plugins cloud_teste