FROM openjdk:19-buster

ENV MB_PLUGINS_DIR=/home/plugins/

ADD https://downloads.metabase.com/v0.52.4/metabase.jar /home
ADD https://github.com/MotherDuck-Open-Source/metabase_duckdb_driver/releases/download/0.2.12/duckdb.metabase-driver.jar /home/plugins/

#COPY . /app

COPY /database/ /data/database
COPY /logs /data/logs

RUN chmod 744 /home/plugins/duckdb.metabase-driver.jar

CMD ["java", "-jar", "/home/metabase.jar"]

#docker run --name metaduck_cloud -d -p 80:3000 -m 2GB -e MB_PLUGINS_DIR=/home/plugins cloud_teste